import { useState, type ReactNode } from 'react';
import { ArrowDown, ArrowUp, BriefcaseBusiness, Check, ChevronDown, FileText, GraduationCap, Lightbulb, Plus, Trash2, UserRound } from 'lucide-react';
import { createId, RESUME_LIMITS, templates, type ResumeDocument, type ResumeProfile } from '../lib/resume';

function Field({ label, value, onChange, multiline = false, placeholder = '', maxLength = RESUME_LIMITS.shortText }: { label:string; value:string; onChange:(value:string)=>void; multiline?:boolean; placeholder?:string; maxLength?:number }) {
  return <label className={`field ${multiline ? 'full-field' : ''}`}><span>{label}</span>{multiline ? <textarea value={value} onChange={(e)=>onChange(e.target.value)} maxLength={maxLength} rows={label==='个人简介'?3:5} placeholder={placeholder}/> : <input value={value} onChange={(e)=>onChange(e.target.value)} maxLength={maxLength} placeholder={placeholder}/>}</label>;
}
function Section({ id, title, icon, detail, open, onToggle, children }: {id:string; title:string; icon:ReactNode; detail?:string;open:boolean;onToggle:()=>void;children:ReactNode}) {
  return <section className={`form-section ${open?'is-open':''}`}><button className="section-toggle" aria-expanded={open} aria-controls={`section-${id}`} onClick={onToggle}>{icon}<strong>{title}</strong><span>{detail}</span><ChevronDown size={19}/></button>{open && <div className="section-content" id={`section-${id}`}>{children}</div>}</section>;
}
export function EditorForm({ resume, onChange, appearance }: {resume:ResumeDocument; onChange:(doc:ResumeDocument)=>void; appearance:boolean}) {
  const [opened,setOpened]=useState('profile');
  const updateProfile=(key:keyof ResumeProfile,value:string)=>onChange({...resume,profile:{...resume.profile,[key]:value}});
  const sections=[{key:'experiences',title:'工作经历',icon:<BriefcaseBusiness/>,name:'公司名称',nameKey:'company',role:'职位名称',roleKey:'role'}, {key:'education',title:'教育经历',icon:<GraduationCap/>,name:'学校名称',nameKey:'school',role:'专业与学历',roleKey:'degree'}, {key:'projects',title:'项目经历',icon:<FileText/>,name:'项目名称',nameKey:'name',role:'担任角色',roleKey:'role'}] as const;
  if (appearance) return <div className="appearance-panel"><h2>选择模板</h2><p>切换模板会保留你填写的全部内容。</p><div className="template-options">{templates.map(t=><button key={t.id} className={`template-option ${resume.templateId===t.id?'selected':''}`} aria-pressed={resume.templateId===t.id} onClick={()=>onChange({...resume,templateId:t.id})}><FileText/><span><strong>{t.name}</strong><small>{t.description}</small></span>{resume.templateId===t.id&&<Check size={18}/>}</button>)}</div><h2>主题颜色</h2><p>为标题、分隔线与侧栏选择一种颜色。</p><div className="swatches">{[{c:'#167d67',n:'森林绿'},{c:'#25375a',n:'海军蓝'},{c:'#7a8663',n:'橄榄绿'},{c:'#a37159',n:'陶土棕'},{c:'#8b4a4a',n:'砖红'},{c:'#333333',n:'石墨黑'}].map(({c,n})=><button key={c} aria-label={n} aria-pressed={resume.accent===c} title={n} style={{background:c}} className={resume.accent===c?'selected':''} onClick={()=>onChange({...resume,accent:c})}>{resume.accent===c&&<Check size={18}/>}</button>)}</div><label className="custom-color">自定义颜色<input aria-label="自定义颜色" type="color" value={resume.accent} onChange={e=>onChange({...resume,accent:e.target.value})}/><span>{resume.accent.toUpperCase()}</span></label><div className="form-tip">页面会随内容自然延长。导出时按 A4 纸张自动分页，空白模块会自动隐藏。</div></div>;
  return <div className="form-sections"><Section id="profile" title="基本信息" icon={<UserRound/>} open={opened==='profile'} onToggle={()=>setOpened(opened==='profile'?'':'profile')}><div className="field-grid"><Field label="姓名" value={resume.profile.name} onChange={v=>updateProfile('name',v)} maxLength={80}/><Field label="求职意向" value={resume.profile.role} onChange={v=>updateProfile('role',v)}/><Field label="电话" value={resume.profile.phone} onChange={v=>updateProfile('phone',v)} maxLength={80}/><Field label="邮箱" value={resume.profile.email} onChange={v=>updateProfile('email',v)} maxLength={254}/><Field label="所在城市" value={resume.profile.city} onChange={v=>updateProfile('city',v)}/><Field label="个人网站" value={resume.profile.website} onChange={v=>updateProfile('website',v)} placeholder="选填，例如：https://" maxLength={500}/><Field label="个人简介" value={resume.profile.summary} onChange={v=>updateProfile('summary',v)} multiline maxLength={RESUME_LIMITS.summary}/></div><div className="character-count">{resume.profile.summary.length} / {RESUME_LIMITS.summary}</div></Section>
  {sections.map(section=>{ const rows=resume[section.key];
    const updateRow=(index:number,key:string,value:string)=>onChange({...resume,[section.key]:rows.map((row,i)=>i===index?{...row,[key]:value}:row)});
    const move=(index:number,direction:number)=>{if(index+direction<0||index+direction>=rows.length)return;const next=[...rows]; [next[index],next[index+direction]]=[next[index+direction],next[index]];onChange({...resume,[section.key]:next});};
    return <Section key={section.key} id={section.key} title={section.title} icon={section.icon} detail={`${rows.length} ${section.key==='projects'?'个项目':'段经历'}`} open={opened===section.key} onToggle={()=>setOpened(opened===section.key?'':section.key)}>{rows.map((row,index)=><div className="entry-form" key={row.id}><div className="entry-actions"><strong>{section.title} {index+1}</strong><button className="icon-button" aria-label={`上移${section.title}${index+1}`} disabled={index===0} onClick={()=>move(index,-1)}><ArrowUp size={15}/></button><button className="icon-button" aria-label={`下移${section.title}${index+1}`} disabled={index===rows.length-1} onClick={()=>move(index,1)}><ArrowDown size={15}/></button><button className="icon-button danger" aria-label={`删除${section.title}${index+1}`} onClick={()=>onChange({...resume,[section.key]:rows.filter((_,i)=>i!==index)})}><Trash2 size={15}/></button></div><div className="field-grid"><Field label={section.name} value={String((row as unknown as Record<string,string>)[section.nameKey])} onChange={v=>updateRow(index,section.nameKey,v)}/><Field label={section.role} value={String((row as unknown as Record<string,string>)[section.roleKey])} onChange={v=>updateRow(index,section.roleKey,v)}/><div className="full-field"><Field label="起止时间" value={row.period} onChange={v=>updateRow(index,'period',v)} placeholder="例如：2023.07 至今"/></div><Field label="经历描述" value={row.description} onChange={v=>updateRow(index,'description',v)} multiline placeholder="写下你的职责与成果，每行一个要点。" maxLength={RESUME_LIMITS.description}/></div></div>)}<button className="button add-entry" disabled={rows.length>=RESUME_LIMITS.sectionEntries} onClick={()=>onChange({...resume,[section.key]:[...rows,{id:createId(),[section.nameKey]:'',[section.roleKey]:'',period:'',description:''}]})}><Plus size={16}/>添加{section.title}</button></Section>;
  })}<Section id="skills" title="专业技能" icon={<Lightbulb/>} open={opened==='skills'} onToggle={()=>setOpened(opened==='skills'?'':'skills')}><Field label="技能与专长" value={resume.skills} onChange={v=>onChange({...resume,skills:v})} multiline maxLength={RESUME_LIMITS.skills} placeholder="例如：Java / Spring Boot / MySQL"/></Section></div>;
}
